#!/bin/bash

echo "📁 Structure du Projet Evolution API v2"
echo "========================================"
echo ""
echo "evolution_wazzap_api/"
echo "├── 📂 local/                          # 🏠 Développement Local"
echo "│   ├── start-local.sh                 # Démarrage simple (standalone)"
echo "│   ├── start-traefik.sh              # Démarrage avec Traefik + Dashboard"
echo "│   ├── stop-local.sh                 # Arrêt des services locaux"
echo "│   ├── stop-traefik.sh               # Arrêt avec Traefik"
echo "│   ├── logs-local.sh                 # Logs en temps réel"
echo "│   ├── docker-compose-traefik.yml    # Config Docker avec Traefik local"
echo "│   └── README.md                     # Guide développement local"
echo "│"
echo "├── 📂 production/                     # 🌐 Production & VPS"
echo "│   ├── setup-vps.sh                  # Installation complète VPS"
echo "│   ├── deploy-single-16gb.sh         # Déploiement 1 serveur 16GB"
echo "│   ├── deploy-2servers.sh            # Déploiement 2 serveurs"
echo "│   ├── deploy-swarm.sh               # Déploiement Docker Swarm"
echo "│   ├── deploy-7k.sh                  # Déploiement 7000 comptes"
echo "│   ├── collect-logs.sh               # Collecte de logs pour debug"
echo "│   ├── docker-compose-single-16gb.yml # Config 1 serveur 16GB"
echo "│   ├── docker-swarm-2servers.yml     # Configuration 2 serveurs"
echo "│   ├── docker-swarm.yml              # Configuration Swarm"
echo "│   ├── docker-swarm-7k.yml           # Configuration 7K comptes"
echo "│   ├── traefik.yml                   # Configuration Traefik production"
echo "│   └── README.md                     # Guide production"
echo "│"
echo "├── 📂 configs/                       # ⚙️ Configurations"
echo "│   ├── config-template.env           # Template complet des variables"
echo "│   ├── production.env                # Variables pour production"
echo "│   └── README.md                     # Guide configurations"
echo "│"
echo "├── 📂 docs/                          # 📚 Documentation"
echo "│   ├── GUIDE-DEPLOIEMENT.md          # Guide de déploiement VPS"
echo "│   ├── README-SCALING.md             # Guide de scaling avancé"
echo "│   └── README.md                     # Index documentation"
echo "│"
echo "├── 📄 docker-compose.yml             # Config Docker principale (standalone)"
echo "├── 📄 SINGLE-SERVER-GUIDE.md         # Guide 1 serveur 16GB"
echo "├── 📄 DEPLOYMENT-7K-GUIDE.md         # Guide de déploiement 2+ serveurs"
echo "├── 📄 scaling-7000-accounts.md       # Plan de scaling 7K comptes"
echo "├── 🧪 test-webhook.sh                # Test configuration webhook"
echo "├── 🧪 test-load-500.sh               # Test de charge 500 instances"
echo "├── 🧪 test-progressive.sh            # Test progressif de capacité"
echo "├── 🧪 test-simple-load.sh            # Test de charge simple"
echo "├── 🧪 test-your-format.sh            # Test avec votre format exact"
echo "├── 🧹 cleanup-except-test4.sh        # Nettoyage préservant TEST4"
echo "├── 🧹 cleanup-instances.sh           # Nettoyage avancé avec options"
echo "├── 🚀 start-local                    # Raccourci démarrage local"
echo "├── 🚀 start-traefik                  # Raccourci démarrage Traefik"
echo "├── 🛑 stop-local                     # Raccourci arrêt local"
echo "├── 🔍 show-structure.sh              # Ce script"
echo "└── 📖 README.md                      # Documentation principale"
echo ""
echo "🎯 Commandes Rapides:"
echo "  ./start-local      # Développement simple"
echo "  ./start-traefik    # Développement avec Traefik"
echo "  ./stop-local       # Arrêter les services"
echo ""
echo "📊 Statistiques:"
echo -n "  Fichiers de script: "
find . -name "*.sh" | wc -l | tr -d ' '
echo -n "  Fichiers de config: "
find . -name "*.yml" -o -name "*.env" | wc -l | tr -d ' '
echo -n "  Fichiers de doc: "
find . -name "*.md" | wc -l | tr -d ' '
echo ""
echo "✅ Projet organisé et prêt à utiliser!"
