version: "3.9"

# Traefik déployé comme SERVICE SWARM (pas container standalone)
# Cela permet une meilleure intégration avec le réseau overlay

services:
  traefik-swarm:
    image: traefik:v3.5.0
    command:
      # Configuration générale
      - "--api.dashboard=true"
      - "--api.insecure=false"
      
      # IMPORTANT: Mode Swarm activé
      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=dokploy-network"
      - "--providers.swarm.refreshSeconds=15"
      
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      
      # SSL Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL:-admin@wazzap.fr}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      
      # Logs
      - "--log.level=INFO"
      - "--log.format=json"
      - "--accesslog=true"
      - "--accesslog.format=json"
      
      # Sécurité
      - "--global.sendAnonymousUsage=false"
    
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    
    networks:
      - dokploy-network
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          # Traefik DOIT être sur le manager
          - node.role == manager
      
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      
      labels:
        # Dashboard Traefik
        - traefik.enable=true
        - traefik.http.routers.traefik-dashboard.rule=Host(`traefik.wazzap.fr`)
        - traefik.http.routers.traefik-dashboard.entrypoints=websecure
        - traefik.http.routers.traefik-dashboard.tls.certresolver=letsencrypt
        - traefik.http.routers.traefik-dashboard.service=api@internal
        - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080

networks:
  dokploy-network:
    external: true
    name: dokploy-network

volumes:
  traefik_letsencrypt:
    name: traefik_letsencrypt

